---
title: "TV Shows - Sinatra"
type: "challenge"
description: "Add acceptance tests to an existing Sinatra application."
tags: "capybara, acceptance-testing, testing, tdd, activerecord, validations"
behaviors:
  - sinatra
  - sinatra_activerecord
  - ruby_and_rspec
  - capybara
ignore:
- "tv-shows-sinatra.md"
